export default [
  [
    'the bigness of cannon',
    'is skilful,',
    'but i have seen',
    'death’s clever enormous voice',
    'which hides in a fragility',
    'of poppies. . . .',
    'i say that sometimes',
    'on these long talkative animals',
    'are laid fists of huger silence.',
    'I have seen all the silence',
    'filled with vivid noiseless boys',
    'at Roupy',
    'i have seen',
    'between barrages,',
    'the night utter ripe unspeaking girls.',
  ],
  [
    'All in green went my love riding',
    'on a great horse of gold',
    'into the silver dawn.',
    'four lean hounds crouched low and smiling',
    'the merry deer ran before.',
    'Fleeter be they than dappled dreams',
    'the swift sweet deer',
    'the red rare deer.',
    'Four red roebuck at a white water',
    'the cruel bugle sang before.',
    'Horn at hip went my love riding',
    'riding the echo down',
    'into the silver dawn.',
    'four lean hounds crouched low and smiling',
    'the level meadows ran before.',
    'Softer be they than slippered sleep',
    'the lean lithe deer',
    'the fleet flown deer.',
    'Four fleet does at a gold valley',
    'the famished arrow sang before.',
    'Bow at belt went my love riding',
    'riding the mountain down',
    'into the silver dawn.',
    'four lean hounds crouched low and smiling',
    'the sheer peaks ran before.',
    'Paler be they than daunting death',
    'the sleek slim deer',
    'the tall tense deer.',
    'Four tall stags at a green mountain',
    'the lucky hunter sang before.',
    'All in green went my love riding',
    'on a great horse of gold',
    'into the silver dawn.',
    'four lean hounds crouched low and smiling',
    'my heart fell dead before.',
  ],
  [
    'as freedom is a breakfastfood',
    'or truth can live with right and wrong',
    'or molehills are from mountains made',
    '—long enough and just so long',
    'will being pay the rent of seem',
    'and genius please the talentgang',
    'and water most encourage flame',
    'as hatracks into peachtrees grow',
    'or hopes dance best on bald men’s hair',
    'and every finger is a toe',
    'and any courage is a fear',
    '—long enough and just so long',
    'will the impure think all things pure',
    'and hornets wail by children stung',
    'or as the seeing are the blind',
    'and robins never welcome spring',
    'nor flatfolk prove their world is round',
    'nor dingsters die at break of dong',
    'and common’s rare and millstones float',
    '—long enough and just so long',
    'tomorrow will not be too late',
    'worms are the words but joy’s the voice',
    'down shall go which and up come who',
    'breasts will be breasts thighs will be thighs',
    'deeds cannot dream what dreams can do',
    '—time is a tree(this life one leaf)',
    'but love is the sky and i am for you',
    'just so long and long enough',
  ],
  [
    'maggie and milly and molly and may',
    'went down to the beach(to play one day)',
    'and maggie discovered a shell that sang',
    "so sweetly she couldn't remember her troubles,and",
    'milly befriended a stranded star',
    'whose rays five languid fingers were;',
    'and molly was chased by a horrible thing',
    'which raced sideways while blowing bubbles:and',
    'may came home with a smooth round stone',
    'as small as a world and as large as alone.',
    'For whatever we lose(like a you or a me)',
    "it's always ourselves we find in the sea",
  ],
  [
    'anyone lived in a pretty how town',
    '(with up so floating many bells down)',
    'spring summer autumn winter',
    "he sang his didn't he danced his did.",
    'Women and men(both little and small)',
    'cared for anyone not at all',
    "they sowed their isn't they reaped their same",
    'sun moon stars rain',
    'children guessed(but only a few',
    'and down they forgot as up they grew',
    'autumn winter spring summer)',
    'that noone loved him more by more',
    'when by now and tree by leaf',
    'she laughed his joy she cried his grief',
    'bird by snow and stir by still',
    "anyone's any was all to her",
    'someones married their everyones',
    'laughed their cryings and did their dance',
    '(sleep wake hope and then)they',
    'said their nevers they slept their dream',
    'stars rain sun moon',
    '(and only the snow can begin to explain',
    'how children are apt to forget to remember',
    'with up so floating many bells down)',
    'one day anyone died i guess',
    '(and noone stooped to kiss his face)',
    'busy folk buried them side by side',
    'little by little and was by was',
    'all by all and deep by deep',
    'and more by more they dream their sleep',
    'noone and anyone earth by april',
    'wish by spirit and if by yes.',
    'Women and men(both dong and ding)',
    'summer autumn winter spring',
    'reaped their sowing and went their came',
    'sun moon stars rain',
  ],
  [
    'pity this busy monster, manunkind,',
    'not. Progress is a comfortable disease:',
    'your victim (death and life safely beyond)',
    'plays with the bigness of his littleness',
    '--- electrons deify one razorblade',
    'into a mountainrange; lenses extend',
    'unwish through curving wherewhen till unwish',
    'returns on its unself.',
    'A world of made',
    'is not a world of born --- pity poor flesh',
    'and trees, poor stars and stones, but never this',
    'fine specimen of hypermagical',
    'ultraomnipotence. We doctors know',
    "a hopeless case if --- listen: there's a hell",
    "of a good universe next door; let's go",
  ],
  [
    'i sing of Olaf glad and big',
    'whose warmest heart recoiled at war:',
    'a conscientious object-or',
    'his wellbelovéd colonel(trig',
    'westpointer most succinctly bred)',
    'took erring Olaf soon in hand;',
    'but--though an host of overjoyed',
    'noncoms(first knocking on the head',
    'him)do through icy waters roll',
    'that helplessness which others stroke',
    'with brushes recently employed',
    'anent this muddy toiletbowl,',
    'while kindred intellects evoke',
    'allegiance per blunt instruments--',
    'Olaf(being to all intents',
    'a corpse and wanting any rag',
    'upon what God unto him gave)',
    'responds,without getting annoyed',
    '"I will not kiss your fucking flag"',
    'straightway the silver bird looked grave',
    '(departing hurriedly to shave)',
    'but--though all kinds of officers',
    "(a yearning nation's blueeyed pride)",
    'their passive prey did kick and curse',
    'until for wear their clarion',
    'voices and boots were much the worse,',
    'and egged the firstclassprivates on',
    'his rectum wickedly to tease',
    'by means of skilfully applied',
    'bayonets roasted hot with heat--',
    'Olaf(upon what were once knees)',
    'does almost ceaselessly repeat',
    '"there is some shit I will not eat"',
    'our president,being of which',
    'assertions duly notified',
    'threw the yellowsonofabitch',
    'into a dungeon,where he died',
    'Christ(of His mercy infinite)',
    'i pray to see;and Olaf,too',
    'preponderatingly because',
    'unless statistics lie he was',
    'more brave than me:more blond than you.',
  ],
]
