name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Wait for Netlify deploy preview
        uses: jakepartusch/wait-for-netlify-action@v1.2
        id: netlify-deploy-preview
        with:
          site_name: 'typonline'
          max_timeout: 360 # 6 Minutes, depends on your build pipeline duration

      - name: Run Playwright tests
        run: cd ./sites/web && pnpm exec playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.netlify-deploy-preview.outputs.url }}
